# Κάνοντας compile το <foo>_test.cpp με μια υλοποίηση <foo>.cpp του
# συγκεκριμένου τύπου, παράγουμε ένα test για την υλοποίηση αυτή.

program_ARGS = ../files/file.txt 100 10 100
program_OBJS = main.o utilities.o child_worker.o parent_worker.o

# Ο βασικός κορμός του Makefile
include ../common.mk
